version: "3"
services:
  - docker

before_install:
  - docker build -t mfundo/multidocker -f ./interface/Dockerfile.dev ./interface

script:
  - docker run mfundo/multidocker  npm test -- --coverage

after_success:
  - docker build -t hypo30cal/multi-api ./api
  - docker build -t hypo30cal/multi-worker ./worker
  - docker build -t hypo30cal/multi-interface ./interface
  - docker build -t hypo30cal/multi-nginx ./nginx
  # Upload the images to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  # Push images to dockerhub
  - docker push hypo30cal/multi-api
  - docker push hypo30cal/multi-worker
  - docker push hypo30cal/multi-interface
  - docker push hypo30cal/multi-nginx